import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, FileCheck2, ReceiptText, XCircle } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { getAudit } from "../api/client";
import type { AuditSummary } from "../api/types";
import { ViewState } from "../components/ViewState";
import { formatDate, formatMoney } from "../lib/format";

export function AuditPage({ date }: { date: string }) {
  const [audit, setAudit] = useState<AuditSummary | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setAudit(null);
    setError(null);
    getAudit(date).then(setAudit).catch((reason: Error) => setError(reason.message));
  }, [date]);

  if (error) return <ViewState title="Audit unavailable" body={error} kind="error" />;
  if (!audit) return <ViewState title="Loading daily audit" body={`Reading the persisted summary for ${date}.`} kind="loading" />;
  if (!audit.sessions) return <ViewState title="No audit results" body="The daily worker has not stored a summary for this date." />;

  const chart = [
    { name: "Validated", value: audit.validated, color: "#31d0aa" },
    { name: "Flagged", value: audit.flagged, color: "#f4b740" },
    { name: "Rejected", value: audit.rejected, color: "#f87171" },
  ];
  const passRate = Math.round((audit.validated / audit.sessions) * 100);

  return (
    <div className="space-y-5">
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <AuditMetric icon={FileCheck2} label="Audited sessions" value={audit.sessions.toLocaleString()} tone="text-sky bg-sky/10" />
        <AuditMetric icon={CheckCircle2} label="Validated" value={audit.validated.toLocaleString()} tone="text-mint bg-mint/10" />
        <AuditMetric icon={AlertTriangle} label="Flagged" value={audit.flagged.toLocaleString()} tone="text-amber bg-amber/10" />
        <AuditMetric icon={XCircle} label="Rejected" value={audit.rejected.toLocaleString()} tone="text-danger bg-danger/10" />
      </div>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
        <section className="border border-line bg-panel p-5 shadow-panel">
          <p className="text-xs font-semibold uppercase text-mint">Daily integrity report</p>
          <h2 className="mt-2 text-2xl font-semibold">{date}</h2>
          <p className="mt-1 text-sm text-slate-500">{audit.createdAt ? `Generated ${formatDate(audit.createdAt)}` : "Generated by the EventBridge audit worker"}</p>
          <div className="mt-8 grid gap-4 sm:grid-cols-2">
            <div className="border border-line bg-ink/40 p-5"><ReceiptText size={18} className="text-violet-300" /><p className="mt-5 text-sm text-slate-500">Estimated revenue</p><p className="mt-2 text-3xl font-semibold">{formatMoney(audit.estimatedRevenue)}</p></div>
            <div className="border border-line bg-ink/40 p-5"><CheckCircle2 size={18} className="text-mint" /><p className="mt-5 text-sm text-slate-500">Validation pass rate</p><p className="mt-2 text-3xl font-semibold">{passRate}%</p></div>
          </div>
          <div className="mt-6 border-l-2 border-sky bg-sky/5 p-4"><p className="text-sm font-semibold">Audit record persisted</p><p className="mt-1 text-xs leading-5 text-slate-500">Stored under PK AUDIT_DAY#{date} and SK SUMMARY for deterministic daily retrieval.</p></div>
        </section>

        <section className="border border-line bg-panel p-5 shadow-panel">
          <h2 className="font-semibold">Outcome distribution</h2>
          <p className="mt-1 text-xs text-slate-500">Final states in the audit window</p>
          <div className="relative h-64">
            <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chart} dataKey="value" innerRadius={70} outerRadius={96} paddingAngle={3} stroke="none">{chart.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip contentStyle={{ background: "#111827", border: "1px solid #273247", borderRadius: 4 }} /></PieChart></ResponsiveContainer>
            <div className="pointer-events-none absolute inset-0 grid place-content-center text-center"><span className="text-3xl font-semibold">{audit.sessions.toLocaleString()}</span><span className="text-[10px] uppercase text-slate-500">Sessions</span></div>
          </div>
          <div className="space-y-3">{chart.map((item) => <div key={item.name} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-slate-400"><span className="h-2 w-2 rounded-full" style={{ background: item.color }} />{item.name}</span><span className="font-semibold">{item.value.toLocaleString()}</span></div>)}</div>
        </section>
      </div>
    </div>
  );
}

function AuditMetric({ icon: Icon, label, value, tone }: { icon: typeof FileCheck2; label: string; value: string; tone: string }) {
  return <article className="border border-line bg-panel p-4 shadow-panel"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{label}</p><span className={`grid h-8 w-8 place-items-center rounded ${tone}`}><Icon size={16} /></span></div><p className="mt-4 text-2xl font-semibold">{value}</p></article>;
}
